### ISSUE TITLE
Error being returned on the UI

### ISSUE THREAD

**Issue by muathendirangu** [tony-nyagah/domain-monitor#1]
Hey @tony-nyagah kindly handle errors and prevent them from being shown on the UI in their raw form, see attached screenshot for context
<img width="1728" alt="Screenshot 2024-01-01 at 18 38 42" src="https://github.com/tony-nyagah/domain-monitor/assets/28337458/99604897-3f3f-464e-ac9d-c1c33ccb0740">

**Comment by tony-nyagah** [comment]
I will hop on this as soon as I can.

**Comment by muathendirangu** [comment]
no worries do you write Golang professionally?

**Comment by muathendirangu** [comment]
also are you open to contributions?

**Comment by tony-nyagah** [comment]
> no worries do you write Golang professionally?

I started learning it last year and am making projects for practice. I'm mostly skilled in Python but I like Go a lot. Any opportunity to work with Go is a win for me.

> also are you open to contributions?

I am very open to making contributions. Best way to learn and improve. I'm willing to take suggestions.

**Comment by muathendirangu** [comment]
> > no worries do you write Golang professionally?
> 
> I started learning it last year and am making projects for practice. I'm mostly skilled in Python but I like Go a lot. Any opportunity to work with Go is a win for me.
> 
> > also are you open to contributions?
> 
> I am very open to making contributions. Best way to learn and improve. I'm willing to take suggestions.

Have a look at the go projects in this org [https://github.com/bitsexplained?q=&type=all&language=go&sort=](bitsexplained) go through them and if you need context ask also we can hop on a call and discuss, you can start by raising a pr(fork the repository first) to update the README based on your understanding or trying to add tests

**Comment by muathendirangu** [comment]
do you work professionally as an engineer?

**Comment by tony-nyagah** [comment]
> do you work professionally as an engineer?

I currently work as a backend developer using Python + Django.
